# Generated by Django 3.2.5 on 2021-07-18 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('REGULAR_USER', 'R'), ('MEMBER', 'M')], max_length=30, null=True, unique=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, choices=[('REGULAR_USER', 'R'), ('MEMBER', 'M')], max_length=30, null=True)),
                ('road_number', models.CharField(blank=True, max_length=10)),
                ('apartment_number', models.CharField(blank=True, max_length=10)),
                ('area', models.CharField(blank=True, max_length=10)),
                ('house_number', models.CharField(blank=True, max_length=10)),
                ('total_amount', models.CharField(blank=True, max_length=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.membership', to_field='type')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Upload_Prescription',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('house', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(blank=True, max_length=10)),
                ('road_number', models.CharField(blank=True, max_length=10)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('area', models.CharField(blank=True, max_length=10)),
                ('delivery_choice', models.CharField(blank=True, choices=[('REGULAR', 'R'), ('EXPRESS', 'E')], max_length=30, null=True)),
                ('collect_choice', models.CharField(blank=True, choices=[('Collect from store', 'CS'), ('Delivery', 'D')], max_length=30, null=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_pres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Product_Info',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='media/post_image')),
                ('price', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('stock', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
